

* {
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	-ms-box-sizing: border-box;
	box-sizing: border-box;
	margin: 0px;
	font-family: 'Bellefair', serif;
}


h3{
	margin-top: 10px;
	font-weight: bold;
}

.corpo{
	font-size: large;
}

.meio{
	margin-top: 20px;
	width: 50%;

}

h2{
	margin-top: 10px;
	margin-bottom: 10px;
}

.objetivo{
	font-weight: bold;
	margin: 2px;
	text-align: center;
	font-size: larger;
	margin-top: 40px;

}

.limite{
	padding-right: 10px;
}

.name {
	text-transform: uppercase;
	font-weight: 100;
	font-size: 300;
}



.row {
	width: 100%;
	display: flex;
	flex-wrap: wrap;
	max-height: 1122px;
	max-width: 790px;
	margin: 0px;

	
}

.col-1 {
	width: 8.33%;
}

.col-2 {
	width: 16.66%;
	max-width: 113.38px;
	max-height: 151.18px;
	text-align: center;
}

.col-3 {
	width: 25%;
	margin-top: 10px;
	margin-bottom: 10px;

}

.col-4 {
	width: 33.33%;
	margin-top: 10px;
	
	text-align: center;
}

.col-5 {
	width: 41.66%;
}

.col-6 {
	width: 50%;
	margin: 10px;
	display: flex;
	flex-wrap: wrap;
	margin-left: 50px;

}

.col-7 {
	width: 58.33%
}

.col-8 {
	width: 66.66%;
	text-align: right;
}

.col-9 {
	width: 75%;
	padding-left: 50px;
	margin-top: 10px;

}

.col-10 {
	width: 83.33%;
	text-align: right;
}

.col-11 {
	width: 91.66%;
}

.col-12 {
	width: 100%;
}
